spring:
  profiles:
    active: local

---
server:
  port: 5959
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  profiles: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://daybook-rds.cjhfreaotcgg.ap-northeast-2.rds.amazonaws.com:3306/daybook
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: guswl9814

jwt:
  secret: djkskwosn@sjdkd!)@*$ksmdlllsoiehdhuw*@(#&!sjkdnallkxjksei!@@*#*@#@&sjklaln

openweather:
  host: https://api.openweathermap.org/data/2.5/weather
  apikey: 3ab9e45e7483aff5ae45a7f6c3f22a92


---
server:
  port: 5959
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mariadb://daybook-rds.cjhfreaotcgg.ap-northeast-2.rds.amazonaws.com:3306/daybook
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: guswl9814

jwt:
  secret: djkskwosn@sjdkd!)@*$ksmdlllsoiehdhuw*@(#&!sjkdnallkxjksei!@@*#*@#@&sjklaln

openweather:
  host: https://api.openweathermap.org/data/2.5/weather
  apikey: 3ab9e45e7483aff5ae45a7f6c3f22a92
